"""Readable BEV occupancy animation for GT-box future trajectories.

This is deliberately a 2D occupancy-style view, rather than a 3D wireframe:
  - gray pixels: current-frame SurroundOcc occupied BEV cells (static context)
  - colored square pixels: each displayed GT box rasterized into occupied cells
  - bright colored ray: real future GT-box-center trajectory used by v7
  - white dot: current animated GT-box center

``gt_agent_fut_trajs`` is not an extra label. It is generated by following the
same instance's future nuScenes GT boxes, then storing their center deltas.

Run on H20:
  /data/chenz/conda_env/splatting/bin/python \
    tools/viz/plot_gtbox_future_occ_anim.py \
    --pkl data/nuscenes_cam/nuscenes_infos_val_gaussian_ad_v4.pkl \
    --data-root . --index -1 \
    --out out/gtbox_trajectory_vis/gtbox_tracks_occ_auto.html
"""
import argparse
import os
import pickle

import numpy as np
import plotly.graph_objects as go


DT = 0.5
STEPS = 6
MOVABLE = {
    'car', 'truck', 'construction_vehicle', 'bus', 'trailer',
    'motorcycle', 'bicycle', 'pedestrian',
}
COLORS = ['#ff3b30', '#007aff', '#34c759', '#ff9500', '#af52de', '#00c7be',
          '#ff2d55', '#5856d6', '#ffcc00', '#64d2ff', '#bf5af2', '#30d158']


def load_infos(path):
    with open(path, 'rb') as handle:
        data = pickle.load(handle)
    infos = data['infos'] if isinstance(data, dict) and 'infos' in data else data
    return [x for frames in infos.values() for x in frames] if isinstance(infos, dict) else infos


def trajectory_data(info):
    boxes = np.asarray(info['gt_boxes'], np.float32)
    names = np.asarray(info.get('gt_names', ['unknown'] * len(boxes))).astype(str)
    delta = np.nan_to_num(np.asarray(info['gt_agent_fut_trajs'], np.float32)).reshape(-1, STEPS, 2)
    valid = np.nan_to_num(np.asarray(info['gt_agent_fut_masks'], np.float32)).reshape(-1, STEPS) > 0.5
    yaw_delta = np.nan_to_num(np.asarray(
        info.get('gt_agent_fut_yaw', np.zeros((len(boxes), STEPS))), np.float32)).reshape(-1, STEPS)
    cumulative = np.cumsum(delta, axis=1)
    cumulative_yaw = np.cumsum(yaw_delta, axis=1)
    extent = np.where(valid, np.linalg.norm(cumulative, axis=-1), 0).max(axis=1)
    movable = np.array([name in MOVABLE for name in names])
    return boxes, names, cumulative, cumulative_yaw, valid, extent, movable


def choose_index(infos, max_boxes, min_motion):
    best, best_score = 0, -1.0
    for index, info in enumerate(infos):
        if 'gt_agent_fut_trajs' not in info:
            continue
        boxes, _, _, _, valid, extent, movable = trajectory_data(info)
        if len(boxes) == 0:
            continue
        candidates = movable & valid.any(axis=1) & (extent >= min_motion)
        score = 100 * min(max_boxes, int(candidates.sum())) + float(extent[candidates].sum())
        if score > best_score:
            best, best_score = index, score
    return best


def load_occ_bev(info, data_root, max_points=25000):
    """Load binary current occupancy projection, downsampled only for HTML size."""
    path = str(info.get('occ_path', ''))
    path = path if os.path.isabs(path) else os.path.join(data_root, path)
    if not path or not os.path.exists(path):
        print(f'[warn] Occ file not found: {path}; using an empty context layer')
        return np.empty((0, 2), np.float32)
    occ = np.load(path)
    # Same 120x120x8 crop and 0.5m metric mapping as dataset occupancy loading.
    i, j, k, label = occ[:, 0], occ[:, 1], occ[:, 2], occ[:, 3]
    keep = ((i >= 40) & (i < 160) & (j >= 40) & (j < 160) &
            (k >= 6) & (k < 14) & (label != 17))
    xy = np.stack([(i[keep] - 40) * 0.5 + 0.25 - 30.0,
                   (j[keep] - 40) * 0.5 + 0.25 - 30.0], axis=1).astype(np.float32)
    # Multiple z voxels share a BEV cell; unique makes a clean occupancy map.
    xy = np.unique(xy, axis=0)
    if len(xy) > max_points:
        xy = xy[np.random.RandomState(0).choice(len(xy), max_points, replace=False)]
    return xy


def raster_box(box, yaw, resolution=0.5):
    """Fill a rotated 2D GT box with square occupancy-cell centers."""
    x, y, _, dx, dy = box[:5]
    radius = max(dx, dy) * 0.75
    gx = np.arange(x - radius, x + radius + resolution, resolution)
    gy = np.arange(y - radius, y + radius + resolution, resolution)
    xx, yy = np.meshgrid(gx, gy, indexing='xy')
    rel_x, rel_y = xx.ravel() - x, yy.ravel() - y
    c, s = np.cos(yaw), np.sin(yaw)
    # world -> box-local rotation by -yaw
    local_x = c * rel_x + s * rel_y
    local_y = -s * rel_x + c * rel_y
    keep = (np.abs(local_x) <= dx / 2) & (np.abs(local_y) <= dy / 2)
    return np.stack([xx.ravel()[keep], yy.ravel()[keep]], axis=1)


def occ_cells_at_step(boxes, names, cumulative, cumulative_yaw, selected, step):
    """Return one occupancy-cell trace payload for all tracked objects at a step."""
    all_xy, all_color, all_text = [], [], []
    centers, center_text = [], []
    for local_id, box_id in enumerate(selected):
        box = boxes[box_id].copy()
        yaw = float(box[6])
        if step:
            box[:2] += cumulative[box_id, step - 1]
            yaw += cumulative_yaw[box_id, step - 1]
        cells = raster_box(box, yaw)
        color = COLORS[local_id % len(COLORS)]
        all_xy.append(cells)
        all_color.extend([color] * len(cells))
        all_text.extend([f'GT occupancy | #{box_id} {names[box_id]}'] * len(cells))
        centers.append(box[:2])
        center_text.append(f'#{box_id} {names[box_id]}')
    return (np.concatenate(all_xy, axis=0), all_color, all_text,
            np.asarray(centers, np.float32), center_text)


def build(info, index, out, data_root, max_boxes, min_motion):
    boxes, names, cumulative, cumulative_yaw, valid, extent, movable = trajectory_data(info)
    chosen = movable & valid.any(axis=1) & (extent >= min_motion)
    selected = np.flatnonzero(chosen)
    selected = selected[np.argsort(extent[selected])[::-1][:max_boxes]]
    if len(selected) == 0:
        raise ValueError('No visible moving GT trajectories. Lower --min-motion or use another --index.')

    context = load_occ_bev(info, data_root)
    paths = []
    traces = [go.Scattergl(
        x=context[:, 0], y=context[:, 1], mode='markers',
        marker=dict(size=4, color='rgba(110,110,110,0.30)', symbol='square'),
        name='current SurroundOcc occupied cells (context)', hoverinfo='skip')]

    # Static trajectory light rays. The animated occupied cells are intentionally
    # separated, keeping the actual GT path legible against the gray context.
    for local_id, box_id in enumerate(selected):
        path = np.concatenate([boxes[box_id, None, :2],
                               boxes[box_id, None, :2] + cumulative[box_id]], axis=0)
        paths.append(path)
        color = COLORS[local_id % len(COLORS)]
        label = f'#{box_id} {names[box_id]} | GT center path | {extent[box_id]:.1f}m'
        traces += [
            go.Scatter(
                x=path[:, 0], y=path[:, 1], mode='lines',
                line=dict(color=color, width=18), opacity=0.16,
                hoverinfo='skip', showlegend=False),
            go.Scatter(
                x=path[:, 0], y=path[:, 1], mode='lines+markers',
                line=dict(color=color, width=4), marker=dict(size=7, color=color),
                name=label, hovertemplate=label + '<extra></extra>'),
        ]

    xy0, colors0, text0, centers0, center_text0 = occ_cells_at_step(
        boxes, names, cumulative, cumulative_yaw, selected, step=0)
    occ_trace_index = len(traces)
    traces.append(go.Scattergl(
        x=xy0[:, 0], y=xy0[:, 1], mode='markers',
        marker=dict(size=10, symbol='square', color=colors0, opacity=0.92),
        name='animated GT-box occupancy cells', text=text0,
        hovertemplate='%{text}<extra></extra>'))
    center_trace_index = len(traces)
    traces.append(go.Scatter(
        x=centers0[:, 0], y=centers0[:, 1], mode='markers+text', text=center_text0,
        textposition='top center', marker=dict(size=9, color='white',
        line=dict(color='#111', width=2)), name='animated GT box centers',
        hovertemplate='%{text}<extra></extra>'))
    traces.append(go.Scatter(
        x=[0], y=[0], mode='markers+text', text=['ego / LiDAR'], textposition='bottom right',
        marker=dict(size=12, color='black', symbol='diamond'), name='ego / LiDAR'))

    frames = []
    for step in range(STEPS + 1):
        xy, colors, text, centers, center_text = occ_cells_at_step(
            boxes, names, cumulative, cumulative_yaw, selected, step)
        frames.append(go.Frame(name=str(step), traces=[occ_trace_index, center_trace_index], data=[
            dict(type='scattergl', x=xy[:, 0], y=xy[:, 1], text=text,
                 marker=dict(size=10, symbol='square', color=colors, opacity=0.92)),
            dict(type='scatter', x=centers[:, 0], y=centers[:, 1], text=center_text),
        ]))

    all_xy = np.concatenate(paths + ([context] if len(context) else []), axis=0)
    pad = 7.0
    xr = [max(-30.0, float(all_xy[:, 0].min() - pad)), min(30.0, float(all_xy[:, 0].max() + pad))]
    yr = [max(-30.0, float(all_xy[:, 1].min() - pad)), min(30.0, float(all_xy[:, 1].max() + pad))]
    labels = ['t=0 (now)'] + [f't={t} (+{t * DT:.1f}s)' for t in range(1, STEPS + 1)]
    slider = dict(active=0, x=0.12, y=0.0, len=0.83, currentvalue=dict(prefix='frame: '),
                  steps=[dict(label=labels[t], method='animate', args=[
                      [str(t)], dict(frame=dict(duration=0, redraw=True), mode='immediate',
                                     transition=dict(duration=0))]) for t in range(STEPS + 1)])
    buttons = dict(type='buttons', direction='left', x=0.0, y=0.0, showactive=False, buttons=[
        dict(label='Play', method='animate', args=[None, dict(
            frame=dict(duration=700, redraw=True), fromcurrent=True, transition=dict(duration=150))]),
        dict(label='Pause', method='animate', args=[[None], dict(
            frame=dict(duration=0, redraw=False), mode='immediate', transition=dict(duration=0))]),
    ])

    fig = go.Figure(data=traces, frames=frames)
    fig.update_layout(
        title=(f'GT-box → future GT-box trajectory supervision | sample {index} | '
               f'{len(selected)} moving instances<br>'
               'gray squares = current Occ context; colored squares = animated GT-box occupancy; '
               'colored rays = real future GT-box center tracks'),
        template='plotly_white', margin=dict(l=5, r=5, t=60, b=42),
        xaxis=dict(title='x: forward (m)', range=xr, scaleanchor='y', scaleratio=1,
                   showgrid=True, gridcolor='#e6e6e6', zeroline=True),
        yaxis=dict(title='y: left (m)', range=yr, showgrid=True, gridcolor='#e6e6e6', zeroline=True),
        legend=dict(x=1.01, y=1.0, bgcolor='rgba(255,255,255,0.8)'),
        updatemenus=[buttons], sliders=[slider], width=1280, height=880,
    )
    fig.write_html(out, include_plotlyjs=True, auto_play=False)
    print(f'saved {out}')
    print(f'index={index} token={info.get("token", "")} selected={selected.tolist()}')


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--pkl', required=True)
    parser.add_argument('--data-root', default='.', help='base directory for relative occ_path')
    parser.add_argument('--out', required=True)
    parser.add_argument('--index', type=int, default=-1, help='-1 = auto-select a rich moving sample')
    parser.add_argument('--max-boxes', type=int, default=8, help='cap shown tracks for readability')
    parser.add_argument('--min-motion', type=float, default=1.0, help='minimum 3s GT displacement (m)')
    args = parser.parse_args()
    infos = load_infos(args.pkl)
    index = args.index if args.index >= 0 else choose_index(infos, args.max_boxes, args.min_motion)
    if not 0 <= index < len(infos):
        raise IndexError(f'index={index} not in [0, {len(infos) - 1}]')
    os.makedirs(os.path.dirname(os.path.abspath(args.out)), exist_ok=True)
    build(infos[index], index, args.out, args.data_root, args.max_boxes, args.min_motion)


if __name__ == '__main__':
    main()